version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.nginx
    volumes:
    - app:/app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 debtcore.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - app:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/debtcore:$PYTHONPATH

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/app
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    command: python -m celery -A debtcore.celery worker -l info -c 4
    ports:
      - 6000:6000

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/app
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    command: celery -A debtcore.celery beat -l info 

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  rabbitmq_data:
  app: